name: Deploy To AWS S3

on:
  push:
    branches:
      - CI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies And Run npm build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}  --exclude './node_modules'